### ISSUE TITLE
quartz/windows

### ISSUE THREAD

**Issue by mdsumner** [ianjonsen/bsam#1]
Replace this with dev.new (or maybe not needed?)

**Comment by mdsumner** [comment]
I think it's not needed, it causes problems with RStudio Server anyway which cannot support dev.new. 

I've pushed the removal of quartz/windows into branch "dev.new" (though it doesn't use dev.new)

**Comment by ianjonsen** [comment]
Agreed. I've removed this from master. New plot functions play nicely with RStudio
