### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by DEHewitt** [ianjonsen/bsam#10]
Hi, I have some acoustic tagging data from a Vemco positioning system that I would like to analyse using your package to estimate behavioural states + account for measurement error in the system. I have been able to get it to run on a very reduced dataset ~150 locations, but my full dataset is ~ 50, 000 from 18 individuals. My concern is the speed of computation. I have access to a high performance cluster and am wondering if the MCMC chains can be run in parallel? Any other tips for speeding up the analysis would be great! Thanks!

**Comment by ianjonsen** [comment]
Hi, 

running bsam in parallel in not really possible. The MCMC chains are run in parallel by default but as independent random processes on a single processor core. As far as I know there are no parallel processing facilities in the underlying JAGS software. You could hack a parallel scenario by running multiple sessions of R + bsam, but I think you will find the reduction in processing time is neglible.

As an alternative, you could try using the `foieGras` R package to fit similar models. Unlike bsam, foieGras uses a much more computationally efficient, frequentist approach which will allow you to fit models to large datasets in reasonable time frames. You can also parallelise the model fitting by distributing the individual datasets across processors using the `future` and `furrr` packages, e.g.:

```
future::plan("multisession")
  fit <-
    x %>% furrr::future_map(~ try(foieGras::fit_ssm(
      d = .x,
      vmax = 5,
      model = "rw",
      time.step = 1
    ), silent = TRUE), .progress = TRUE) %>%
    do.call(rbind, .)
```

where `x` is your data as a nested tibble with each row corresponding to an individual `id`, and `fit_ssm` is the `foieGras` function used to fit the SSM. See `?fit_ssm` and the `foieGras` vignette for more details. 

You could then use `foieGras::fit_mpm` to estimate a behavioural index that is roughly analogous to the behavioural states estimated by bsam, though I can make no guarantees that this will work for acoustic data as I have not explored this.

HTH

Ian

**Comment by DEHewitt** [comment]
Thanks for the suggestion. I'll check it out!

**Comment by Alynvince** [comment]
Hello Ian, 

I used your code on my data with the new aniMotum package. The outcome however is a dataframe with the error argument "x" is missing, with no default. I have added a snippet of my data, your slightly modified code and the outcome below.  Could you help me identify the cause of the error ? In total, I have 4000 segmented tracks (with a minimum segment length of 10 locations per segment) to run, hence your parallel code will be of great help. 

Thank you, 

Aly

My data : 
```
structure(list(id = c("228757_2", "228757_3", "228757_5"), data = list(
    structure(list(date = structure(c(1674904479, 1674908254, 
    1674910798, 1674912856, 1674914006, 1674914399, 1674916195, 
    1674916713, 1674918730, 1674920335), tzone = "UTC", class = c("POSIXct", 
    "POSIXt")), lc = c("3", "1", "A", "2", "B", "3", "B", "A", 
    "2", "2"), lon = c(-63.2201, -63.2036, -63.2252, -63.2129, 
    -63.1992, -63.2134, -63.2119, -63.2103, -63.2224, -63.2238
    ), lat = c(45.8787, 45.8812, 45.8873, 45.8847, 45.8828, 45.8834, 
    45.8862, 45.8841, 45.8875, 45.887), smaj = c(332L, 28941L, 
    8133L, 415L, 10255L, 245L, 3034L, 4050L, 586L, 822L), smin = c(164L, 
    62L, 217L, 174L, 3982L, 168L, 511L, 67L, 135L, 81L), eor = c(132L, 
    100L, 87L, 89L, 98L, 68L, 94L, 90L, 96L, 100L)), row.names = c(NA, 
    -10L), class = c("tbl_df", "tbl", "data.frame")), structure(list(
        date = structure(c(1674940254, 1674942766, 1674943151, 
        1674945865, 1674947986, 1674951198, 1674951983, 1674954046, 
        1674955129, 1674955614, 1674956968, 1674958329, 1674960308
        ), tzone = "UTC", class = c("POSIXct", "POSIXt")), lc = c("B", 
        "3", "3", "3", "3", "B", "3", "1", "B", "2", "A", "B", 
        "A"), lon = c(-63.2343, -63.233, -63.233, -63.2216, -63.2151, 
        -63.2097, -63.192, -63.1821, -63.1803, -63.1569, -63.161, 
        -63.1599, -63.1592), lat = c(45.9114, 45.9098, 45.9065, 
        45.9269, 45.9247, 45.9288, 45.9245, 45.9241, 45.9245, 
        45.9166, 45.9101, 45.91, 45.9071), smaj = c(15089L, 270L, 
        364L, 275L, 246L, 1393L, 397L, 18535L, 3412L, 1362L, 
        5725L, 1527L, 1514L), smin = c(2178L, 147L, 137L, 108L, 
        140L, 686L, 55L, 54L, 961L, 65L, 105L, 440L, 162L), eor = c(100L, 
        24L, 88L, 59L, 92L, 83L, 93L, 78L, 83L, 77L, 88L, 90L, 
        40L)), row.names = c(NA, -13L), class = c("tbl_df", "tbl", 
    "data.frame")), structure(list(date = structure(c(1675027746, 
    1675028556, 1675031994, 1675033408, 1675033845, 1675034093, 
    1675035638, 1675036510, 1675037784, 1675039350, 1675039684, 
    1675041582, 1675042067), tzone = "UTC", class = c("POSIXct", 
    "POSIXt")), lc = c("3", "A", "1", "A", "1", "A", "A", "B", 
    "1", "3", "3", "A", "A"), lon = c(-63.1889, -63.1959, -63.2246, 
    -63.2243, -63.2151, -63.2281, -63.2301, -63.2314, -63.2262, 
    -63.2344, -63.2304, -63.2396, -63.2438), lat = c(45.7721, 
    45.771, 45.7782, 45.782, 45.7906, 45.7898, 45.7937, 45.7929, 
    45.799, 45.7966, 45.7858, 45.7871, 45.7823), smaj = c(377L, 
    199L, 3807L, 1826L, 6404L, 360L, 1713L, 1349L, 1673L, 479L, 
    386L, 444L, 312L), smin = c(101L, 113L, 101L, 187L, 62L, 
    110L, 135L, 385L, 160L, 56L, 117L, 70L, 102L), eor = c(119L, 
    0L, 83L, 109L, 79L, 83L, 113L, 104L, 76L, 76L, 139L, 56L, 
    58L)), row.names = c(NA, -13L), class = c("tbl_df", "tbl", 
    "data.frame")))), row.names = c(NA, -3L), class = c("tbl_df", 
"tbl", "data.frame"))
```

Your code 
```
future::plan("multisession")
fit <- data %>% furrr::future_map(~ try(aniMotum::fit_ssm(
      d = .x,
      vmax = 2,
      model = "crw",
      time.step = 1, 
      control = ssm_control(verbose = 0)), 
      silent = TRUE), .progress = TRUE, seed = TRUE) %>%
    do.call(rbind, .)
```

The output 

```
structure(c("Error in aniMotum::fit_ssm(d = data$data, vmax = 2, model = \"crw\", time.step = 1,  : \n  argument \"x\" is missing, with no default\n", 
"Error in aniMotum::fit_ssm(d = data$data, vmax = 2, model = \"crw\", time.step = 1,  : \n  argument \"x\" is missing, with no default\n"
), dim = 2:1, dimnames = list(c("id", "data"), NULL))
```

**Comment by ianjonsen** [comment]
Hi Aly,

A couple of issues here, first your nested tibble `data` needs to be restructured. The simplest approach is to `unnest()` & then use `split()`:
```
data <- unnest(data, cols = data) 
data <- split(data, data$id)
```

The point being, you need the `id` variable to be in each of the three data.frame's as that's what `fit_ssm()` requires. 

Second, I think you found older parallelization code. This slightly different approach works with `aniMotum` v 1.2-04 & `furrr` 0.3.1:
```
require(tidyverse)
require(aniMotum)

future::plan("multisession")
fit <- data %>% 
    furrr::future_map(~ try(fit_ssm(
        x = .x,
        vmax = 2,
        model = "crw",
        time.step = 1,
        control = ssm_control(verbose = 0)
    ), silent = TRUE),
    .progress = TRUE,
    .options = furrr::furrr_options(seed = TRUE)
    ) %>%
    bind_rows(.)
```

Cheers, Ian
