### ISSUE TITLE
cleanup argument doc

### ISSUE THREAD

**Issue by mdsumner** [ianjonsen/bsam#2]
"tod" param was in Rd but not in dat4jags
simTrack has undocumented params, including "T" which maybe should be renamed

Undocumented arguments in documentation object 'ssm' 'adapt' 'samples' 'thin' 'chains' Argument items with no description in Rd object 'diagSSM': 'fit.in' 'save.to.pdf'
Argument items with no description in Rd object 'hssm': 'loc.list' 'model' 'adapt' 'samples' 'thin' 'chains' '...'

Argument items with no description in Rd object 'plotSSM': 'fit.in' 'save.to.pdf'

Argument items with no description in Rd object 'simTrack': 'theta' 'gamma' 'alpha' 'vcov'

**Comment by ianjonsen** [comment]
working on streamlined dat4jags, ssm/hssm, and simTrack functions, will also fix argument documentation in these

**Comment by ianjonsen** [comment]
All documentation has been cleaned up. Should be near complete
