### ISSUE TITLE
prepare for release

### ISSUE THREAD

**Issue by mdsumner** [ianjonsen/bsam#4]
this is a checklist of sorts, of things that R CMD check reports
- fix version number for release
- ensure long examples and tests are not run (maybe set up auto-tests, or publish run examples in the README)
- d and span args need doc in fitSSM
- not sure if setting NULL value for countriesHigh fixes the issue with hidden global variables (seems to work)

**Comment by ianjonsen** [comment]
version number for release is updated to 1.0.0

**Comment by ianjonsen** [comment]
d (changed to data) and span are now properly documented in fit_ssm
