### ISSUE TITLE
deprecated functions

### ISSUE THREAD

**Issue by mdsumner** [ianjonsen/bsam#6]
Renaming functions is pretty disruptive!  You can use "deprecated" to point users to the new way. 

Add this in a new file "R/bsam-deprecated.R": 

``` r
#' Deprecated functions. 
#' 
#' \code{fitSSM} and \code{dplot} and \code{tplot} have been deprecated. Instead use
#' \code{fit_ssm}, \code{diag_ssm} and \code{map_ssm}.
#' @rdname bsam-deprecated
#' @param ... ignored
#' @export
#' @rdname bsam-deprecated 
fitSSM <- function(...) {
  .Deprecated("fit_ssm")
}

#' @export
#' @rdname bsam-deprecated
dplot <- function(...) {
  .Deprecated("diag_ssm")
}

#' @export
#' @rdname bsam-deprecated
tplot <- function(...) {
  .Deprecated("map_ssm")
}


```

**Comment by ianjonsen** [comment]
yes, wasn't thinking that completely through. Done, but dropped dplot and tplot as these were both new function names in dev builds 0.43.1.9001-9003. diagSSM and plotSSM were the analogous functions in the previous release.
