### ISSUE TITLE
Error when using fit_ssm

### ISSUE THREAD

**Issue by lidefi87** [ianjonsen/bsam#9]
I tried using the fit_ssm function on my data, which has been changed to fit the requirements of this function, and it came up with this error:

Error: Can't join on `x$lc` x `y$lc` because of incompatible types.
i `x$lc` is of type <ordered<d6411>>>.
i `y$lc` is of type <ordered<3e9dd>>>.

After trying a few changes in my data, I kept getting the same error, so I tried using the ellie dataset included in your package and I got the same error above. Running rlang::last_error() gives me the following information:

Backtrace:
  1. bsam::fit_ssm(...)
  2. bsam::dat4jags(data, tstep = tstep, tpar = tpar())
  4. dplyr:::left_join.data.frame(d, tpar, by = "lc")
  5. dplyr:::join_mutate(...)
  6. dplyr:::join_rows(x_key, y_key, type = type, na_equal = na_equal)
  7. base::tryCatch(...)
  8. base:::tryCatchList(expr, classes, parentenv, handlers)
  9. base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 10. value[[3L]](cond)

It seems there is a problem at some point with joining data. I have not looked into it further, but I thought I should report it.

**Comment by rlambourne** [comment]
I have found this same issue.. have you come across a solution by any chance?

**Comment by lidefi87** [comment]
No, not yet, I have not had the chance. I am hoping to do this in the next few weeks.

**Comment by ianjonsen** [comment]
Thanks for reporting this. Version 1.1.3 addresses this issue - available only via this GitHub. I have yet to test on Windows & Linux platforms. Update to CRAN version (currently 1.1.2) will come once testing is complete.
